package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActivityEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityEventAllPropertiesEquals(ActivityEvent expected, ActivityEvent actual) {
        assertActivityEventAutoGeneratedPropertiesEquals(expected, actual);
        assertActivityEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityEventAllUpdatablePropertiesEquals(ActivityEvent expected, ActivityEvent actual) {
        assertActivityEventUpdatableFieldsEquals(expected, actual);
        assertActivityEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityEventAutoGeneratedPropertiesEquals(ActivityEvent expected, ActivityEvent actual) {
        assertThat(actual)
            .as("Verify ActivityEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityEventUpdatableFieldsEquals(ActivityEvent expected, ActivityEvent actual) {
        assertThat(actual)
            .as("Verify ActivityEvent relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getActorName()).as("check actorName").isEqualTo(expected.getActorName()))
            .satisfies(a -> assertThat(a.getTargetTitle()).as("check targetTitle").isEqualTo(expected.getTargetTitle()))
            .satisfies(a -> assertThat(a.getDetail()).as("check detail").isEqualTo(expected.getDetail()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityEventUpdatableRelationshipsEquals(ActivityEvent expected, ActivityEvent actual) {
        assertThat(actual)
            .as("Verify ActivityEvent relationships")
            .satisfies(a -> assertThat(a.getSpace()).as("check space").isEqualTo(expected.getSpace()))
            .satisfies(a -> assertThat(a.getPage()).as("check page").isEqualTo(expected.getPage()));
    }
}
