package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachmentAllPropertiesEquals(Attachment expected, Attachment actual) {
        assertAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachmentAllUpdatablePropertiesEquals(Attachment expected, Attachment actual) {
        assertAttachmentUpdatableFieldsEquals(expected, actual);
        assertAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachmentAutoGeneratedPropertiesEquals(Attachment expected, Attachment actual) {
        assertThat(actual)
            .as("Verify Attachment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachmentUpdatableFieldsEquals(Attachment expected, Attachment actual) {
        assertThat(actual)
            .as("Verify Attachment relevant properties")
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getMimeType()).as("check mimeType").isEqualTo(expected.getMimeType()))
            .satisfies(a -> assertThat(a.getSize()).as("check size").isEqualTo(expected.getSize()))
            .satisfies(a -> assertThat(a.getSha256()).as("check sha256").isEqualTo(expected.getSha256()))
            .satisfies(a -> assertThat(a.getGitPath()).as("check gitPath").isEqualTo(expected.getGitPath()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachmentUpdatableRelationshipsEquals(Attachment expected, Attachment actual) {
        assertThat(actual)
            .as("Verify Attachment relationships")
            .satisfies(a -> assertThat(a.getPage()).as("check page").isEqualTo(expected.getPage()));
    }
}
