package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PageWatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageWatchAllPropertiesEquals(PageWatch expected, PageWatch actual) {
        assertPageWatchAutoGeneratedPropertiesEquals(expected, actual);
        assertPageWatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageWatchAllUpdatablePropertiesEquals(PageWatch expected, PageWatch actual) {
        assertPageWatchUpdatableFieldsEquals(expected, actual);
        assertPageWatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageWatchAutoGeneratedPropertiesEquals(PageWatch expected, PageWatch actual) {
        assertThat(actual)
            .as("Verify PageWatch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageWatchUpdatableFieldsEquals(PageWatch expected, PageWatch actual) {
        assertThat(actual)
            .as("Verify PageWatch relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageWatchUpdatableRelationshipsEquals(PageWatch expected, PageWatch actual) {
        assertThat(actual)
            .as("Verify PageWatch relationships")
            .satisfies(a -> assertThat(a.getPage()).as("check page").isEqualTo(expected.getPage()));
    }
}
