package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageAllPropertiesEquals(Page expected, Page actual) {
        assertPageAutoGeneratedPropertiesEquals(expected, actual);
        assertPageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageAllUpdatablePropertiesEquals(Page expected, Page actual) {
        assertPageUpdatableFieldsEquals(expected, actual);
        assertPageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageAutoGeneratedPropertiesEquals(Page expected, Page actual) {
        assertThat(actual)
            .as("Verify Page auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageUpdatableFieldsEquals(Page expected, Page actual) {
        assertThat(actual)
            .as("Verify Page relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getKind()).as("check kind").isEqualTo(expected.getKind()))
            .satisfies(a -> assertThat(a.getGitPath()).as("check gitPath").isEqualTo(expected.getGitPath()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getSyncStatus()).as("check syncStatus").isEqualTo(expected.getSyncStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageUpdatableRelationshipsEquals(Page expected, Page actual) {
        assertThat(actual)
            .as("Verify Page relationships")
            .satisfies(a -> assertThat(a.getCurrentVersion()).as("check currentVersion").isEqualTo(expected.getCurrentVersion()))
            .satisfies(a -> assertThat(a.getLabelses()).as("check labelses").isEqualTo(expected.getLabelses()))
            .satisfies(a -> assertThat(a.getSpace()).as("check space").isEqualTo(expected.getSpace()))
            .satisfies(a -> assertThat(a.getParent()).as("check parent").isEqualTo(expected.getParent()));
    }
}
