package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PageDraftAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageDraftAllPropertiesEquals(PageDraft expected, PageDraft actual) {
        assertPageDraftAutoGeneratedPropertiesEquals(expected, actual);
        assertPageDraftAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageDraftAllUpdatablePropertiesEquals(PageDraft expected, PageDraft actual) {
        assertPageDraftUpdatableFieldsEquals(expected, actual);
        assertPageDraftUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageDraftAutoGeneratedPropertiesEquals(PageDraft expected, PageDraft actual) {
        assertThat(actual)
            .as("Verify PageDraft auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageDraftUpdatableFieldsEquals(PageDraft expected, PageDraft actual) {
        assertThat(actual)
            .as("Verify PageDraft relevant properties")
            .satisfies(a -> assertThat(a.getContentMd()).as("check contentMd").isEqualTo(expected.getContentMd()))
            .satisfies(a -> assertThat(a.getBaseVersionNo()).as("check baseVersionNo").isEqualTo(expected.getBaseVersionNo()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageDraftUpdatableRelationshipsEquals(PageDraft expected, PageDraft actual) {
        assertThat(actual)
            .as("Verify PageDraft relationships")
            .satisfies(a -> assertThat(a.getPage()).as("check page").isEqualTo(expected.getPage()));
    }
}
