package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PageVersionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageVersionAllPropertiesEquals(PageVersion expected, PageVersion actual) {
        assertPageVersionAutoGeneratedPropertiesEquals(expected, actual);
        assertPageVersionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageVersionAllUpdatablePropertiesEquals(PageVersion expected, PageVersion actual) {
        assertPageVersionUpdatableFieldsEquals(expected, actual);
        assertPageVersionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageVersionAutoGeneratedPropertiesEquals(PageVersion expected, PageVersion actual) {
        assertThat(actual)
            .as("Verify PageVersion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageVersionUpdatableFieldsEquals(PageVersion expected, PageVersion actual) {
        assertThat(actual)
            .as("Verify PageVersion relevant properties")
            .satisfies(a -> assertThat(a.getVersionNo()).as("check versionNo").isEqualTo(expected.getVersionNo()))
            .satisfies(a -> assertThat(a.getContentMd()).as("check contentMd").isEqualTo(expected.getContentMd()))
            .satisfies(a -> assertThat(a.getContentSha256()).as("check contentSha256").isEqualTo(expected.getContentSha256()))
            .satisfies(a -> assertThat(a.getAuthorName()).as("check authorName").isEqualTo(expected.getAuthorName()))
            .satisfies(a -> assertThat(a.getAuthorEmail()).as("check authorEmail").isEqualTo(expected.getAuthorEmail()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getGitCommit()).as("check gitCommit").isEqualTo(expected.getGitCommit()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageVersionUpdatableRelationshipsEquals(PageVersion expected, PageVersion actual) {
        assertThat(actual)
            .as("Verify PageVersion relationships")
            .satisfies(a -> assertThat(a.getPage()).as("check page").isEqualTo(expected.getPage()));
    }
}
