package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SpaceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpaceAllPropertiesEquals(Space expected, Space actual) {
        assertSpaceAutoGeneratedPropertiesEquals(expected, actual);
        assertSpaceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpaceAllUpdatablePropertiesEquals(Space expected, Space actual) {
        assertSpaceUpdatableFieldsEquals(expected, actual);
        assertSpaceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpaceAutoGeneratedPropertiesEquals(Space expected, Space actual) {
        assertThat(actual)
            .as("Verify Space auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpaceUpdatableFieldsEquals(Space expected, Space actual) {
        assertThat(actual)
            .as("Verify Space relevant properties")
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getGitRepoUrl()).as("check gitRepoUrl").isEqualTo(expected.getGitRepoUrl()))
            .satisfies(a -> assertThat(a.getGitBranch()).as("check gitBranch").isEqualTo(expected.getGitBranch()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getArchived()).as("check archived").isEqualTo(expected.getArchived()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpaceUpdatableRelationshipsEquals(Space expected, Space actual) {
        // empty method
    }
}
