package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SyncRootAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncRootAllPropertiesEquals(SyncRoot expected, SyncRoot actual) {
        assertSyncRootAutoGeneratedPropertiesEquals(expected, actual);
        assertSyncRootAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncRootAllUpdatablePropertiesEquals(SyncRoot expected, SyncRoot actual) {
        assertSyncRootUpdatableFieldsEquals(expected, actual);
        assertSyncRootUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncRootAutoGeneratedPropertiesEquals(SyncRoot expected, SyncRoot actual) {
        assertThat(actual)
            .as("Verify SyncRoot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncRootUpdatableFieldsEquals(SyncRoot expected, SyncRoot actual) {
        assertThat(actual)
            .as("Verify SyncRoot relevant properties")
            .satisfies(a -> assertThat(a.getRepoPath()).as("check repoPath").isEqualTo(expected.getRepoPath()))
            .satisfies(a -> assertThat(a.getEnabled()).as("check enabled").isEqualTo(expected.getEnabled()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncRootUpdatableRelationshipsEquals(SyncRoot expected, SyncRoot actual) {
        assertThat(actual)
            .as("Verify SyncRoot relationships")
            .satisfies(a -> assertThat(a.getMountPage()).as("check mountPage").isEqualTo(expected.getMountPage()))
            .satisfies(a -> assertThat(a.getSpace()).as("check space").isEqualTo(expected.getSpace()));
    }
}
