package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SyncStateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncStateAllPropertiesEquals(SyncState expected, SyncState actual) {
        assertSyncStateAutoGeneratedPropertiesEquals(expected, actual);
        assertSyncStateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncStateAllUpdatablePropertiesEquals(SyncState expected, SyncState actual) {
        assertSyncStateUpdatableFieldsEquals(expected, actual);
        assertSyncStateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncStateAutoGeneratedPropertiesEquals(SyncState expected, SyncState actual) {
        assertThat(actual)
            .as("Verify SyncState auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncStateUpdatableFieldsEquals(SyncState expected, SyncState actual) {
        assertThat(actual)
            .as("Verify SyncState relevant properties")
            .satisfies(a -> assertThat(a.getLastSyncedCommit()).as("check lastSyncedCommit").isEqualTo(expected.getLastSyncedCommit()))
            .satisfies(a -> assertThat(a.getLastFetchAt()).as("check lastFetchAt").isEqualTo(expected.getLastFetchAt()))
            .satisfies(a -> assertThat(a.getLastPushAt()).as("check lastPushAt").isEqualTo(expected.getLastPushAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncStateUpdatableRelationshipsEquals(SyncState expected, SyncState actual) {
        assertThat(actual)
            .as("Verify SyncState relationships")
            .satisfies(a -> assertThat(a.getSyncRoot()).as("check syncRoot").isEqualTo(expected.getSyncRoot()));
    }
}
