package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SyncConflictAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncConflictAllPropertiesEquals(SyncConflict expected, SyncConflict actual) {
        assertSyncConflictAutoGeneratedPropertiesEquals(expected, actual);
        assertSyncConflictAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncConflictAllUpdatablePropertiesEquals(SyncConflict expected, SyncConflict actual) {
        assertSyncConflictUpdatableFieldsEquals(expected, actual);
        assertSyncConflictUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncConflictAutoGeneratedPropertiesEquals(SyncConflict expected, SyncConflict actual) {
        assertThat(actual)
            .as("Verify SyncConflict auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncConflictUpdatableFieldsEquals(SyncConflict expected, SyncConflict actual) {
        assertThat(actual)
            .as("Verify SyncConflict relevant properties")
            .satisfies(a -> assertThat(a.getGitContentMd()).as("check gitContentMd").isEqualTo(expected.getGitContentMd()))
            .satisfies(a -> assertThat(a.getGitCommit()).as("check gitCommit").isEqualTo(expected.getGitCommit()))
            .satisfies(a -> assertThat(a.getDetectedAt()).as("check detectedAt").isEqualTo(expected.getDetectedAt()))
            .satisfies(a -> assertThat(a.getResolvedAt()).as("check resolvedAt").isEqualTo(expected.getResolvedAt()))
            .satisfies(a -> assertThat(a.getResolution()).as("check resolution").isEqualTo(expected.getResolution()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncConflictUpdatableRelationshipsEquals(SyncConflict expected, SyncConflict actual) {
        assertThat(actual)
            .as("Verify SyncConflict relationships")
            .satisfies(a -> assertThat(a.getPage()).as("check page").isEqualTo(expected.getPage()))
            .satisfies(a -> assertThat(a.getBaseVersion()).as("check baseVersion").isEqualTo(expected.getBaseVersion()))
            .satisfies(a -> assertThat(a.getWikiVersion()).as("check wikiVersion").isEqualTo(expected.getWikiVersion()));
    }
}
