package com.yuzhi.dts.wiki.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SyncOutboxAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncOutboxAllPropertiesEquals(SyncOutbox expected, SyncOutbox actual) {
        assertSyncOutboxAutoGeneratedPropertiesEquals(expected, actual);
        assertSyncOutboxAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncOutboxAllUpdatablePropertiesEquals(SyncOutbox expected, SyncOutbox actual) {
        assertSyncOutboxUpdatableFieldsEquals(expected, actual);
        assertSyncOutboxUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncOutboxAutoGeneratedPropertiesEquals(SyncOutbox expected, SyncOutbox actual) {
        assertThat(actual)
            .as("Verify SyncOutbox auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncOutboxUpdatableFieldsEquals(SyncOutbox expected, SyncOutbox actual) {
        assertThat(actual)
            .as("Verify SyncOutbox relevant properties")
            .satisfies(a -> assertThat(a.getOp()).as("check op").isEqualTo(expected.getOp()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()))
            .satisfies(a -> assertThat(a.getActorLogin()).as("check actorLogin").isEqualTo(expected.getActorLogin()))
            .satisfies(a -> assertThat(a.getActorName()).as("check actorName").isEqualTo(expected.getActorName()))
            .satisfies(a -> assertThat(a.getActorEmail()).as("check actorEmail").isEqualTo(expected.getActorEmail()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAttempts()).as("check attempts").isEqualTo(expected.getAttempts()))
            .satisfies(a -> assertThat(a.getLastError()).as("check lastError").isEqualTo(expected.getLastError()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getProcessedAt()).as("check processedAt").isEqualTo(expected.getProcessedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSyncOutboxUpdatableRelationshipsEquals(SyncOutbox expected, SyncOutbox actual) {
        assertThat(actual)
            .as("Verify SyncOutbox relationships")
            .satisfies(a -> assertThat(a.getSpace()).as("check space").isEqualTo(expected.getSpace()))
            .satisfies(a -> assertThat(a.getPage()).as("check page").isEqualTo(expected.getPage()));
    }
}
